#ifndef SASSYTALKIE_IOS_H
#define SASSYTALKIE_IOS_H

/* Generated with cbindgen:0.29.4 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
namespace sassytalkie {
#endif  // __cplusplus

/**
 * Sample rate (48kHz for Opus)
 */
#define SAMPLE_RATE 48000

/**
 * Frame size (20ms at 48kHz = 960 samples)
 */
#define FRAME_SIZE 960

/**
 * Frame duration (20ms)
 */
#define FRAME_DURATION_MS 20

/**
 * Multicast port
 */
#define MULTICAST_PORT 5555

#define PRESENCE_IDLE 0

#define PRESENCE_SPEAKING 2

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Initialize the library
 * 
 * # Safety
 * This function must be called before any other library functions
 */
bool sassytalkie_init(void);

/**
 * Shutdown the library
 */
void sassytalkie_shutdown(void);

/**
 * Get version string
 * 
 * # Safety
 * Caller must free the returned string with `sassytalkie_free_string`
 */
const char *sassytalkie_get_version(void);

/**
 * Free a string allocated by the library
 * 
 * # Safety
 * Pointer must have been returned by a library function
 */
void sassytalkie_free_string(char *s);

/**
 * Install a pre-shared key (the QR session key) from base64. Returns true on
 * success. After this, TX frames are AES-256-GCM encrypted and RX frames are
 * decrypted (+ replay-checked).
 */
bool sassytalkie_set_psk(const char *key_b64);

/**
 * Import a scanned QR session — the JSON an Android/desktop host generates.
 * Switches to the QR's channel and installs its key, reusing the SHARED core
 * validation so iOS accepts/rejects exactly the QRs Android does. Returns the
 * channel (1-8) on success, or 0 on a malformed / expired QR. This is the
 * cross-platform pairing entry point: scan a host's QR → encrypted audio flows.
 */
uint8_t sassytalkie_import_session_qr(const char *qr_json);

/**
 * Decrypt a session-invite share blob (the bytes from `GET /share/<id>`) using
 * the url-safe-base64 key from the invite link's `#fragment`, via the SHARED
 * core. Returns the decrypted session-QR JSON (free with
 * `sassytalkie_free_string`) to hand straight to `sassytalkie_import_session_qr`,
 * or null on bad input / wrong key / tampered blob.
 *
 * `blob_ptr`/`blob_len` are the raw relay bytes (`IV‖ciphertext+tag`). The key
 * never reaches the relay, so a KV dump is useless. This is the iOS half of the
 * `/v/<id>#<key>` invite import — the exact `core::share` path Android (Kotlin)
 * and desktop (Tauri) use.
 */
char *sassytalkie_decrypt_share_blob(const uint8_t *blob_ptr,
                                     uintptr_t blob_len,
                                     const char *key_b64url);

/**
 * Host a channel: mint a fresh session QR (the JSON another device scans) and
 * install its key locally so the host can TX/RX on this channel too. Returns the
 * QR JSON to render (free with sassytalkie_free_string), or null on failure.
 * `group_name` may be null/empty ("Channel N"); duration clamps to 1..=72 h.
 */
char *sassytalkie_generate_session_qr(uint8_t channel,
                                      uint32_t duration_hours,
                                      const char *group_name);

/**
 * Begin a classical X25519 key exchange. Returns our base64 public key (free
 * with sassytalkie_free_string), or null. Complete with
 * sassytalkie_key_exchange_complete.
 */
char *sassytalkie_key_exchange_init(void);

/**
 * Complete the classical key exchange with the peer's base64 public key,
 * installing the AEAD session. Returns true on success.
 */
bool sassytalkie_key_exchange_complete(const char *remote_b64);

/**
 * Wipe session keys, control plane, and staged hybrid. In-app hook; MDM/EMM
 * must trigger this for remote logout.
 */
void sassytalkie_wipe_session(void);

/**
 * Technical audit JSON (free with sassytalkie_free_string). Not a legal chain of custody.
 */
char *sassytalkie_export_audit(void);

bool sassytalkie_set_enrollment_token(const char *token);

bool sassytalkie_hybrid_handshake_confirm(void);

/**
 * This build's capability bitmap (hybrid-PQC support) — same value Android
 * advertises in its heartbeat caps byte.
 */
uint8_t sassytalkie_local_capabilities(void);

/**
 * Initiator: begin a path-(a) PSK-authenticated hybrid handshake. Returns the
 * base64 initiator message (free with sassytalkie_free_string), or null if no
 * PSK is installed / not initialized.
 */
char *sassytalkie_hybrid_handshake_init(void);

/**
 * Responder: given the peer's base64 initiator message, install the session and
 * return the base64 responder message (free with sassytalkie_free_string), or
 * null on failure.
 */
char *sassytalkie_hybrid_handshake_respond(const char *init_b64);

/**
 * Initiator: complete with the peer's base64 responder message, installing the
 * post-quantum session. Returns true on success. Must follow a
 * sassytalkie_hybrid_handshake_init on this device.
 */
bool sassytalkie_hybrid_handshake_complete(const char *resp_b64);

/**
 * Free a buffer returned by `sassytalkie_relay_poll_outbound` /
 * `sassytalkie_relay_heartbeat_frame`.
 *
 * # Safety
 * `ptr`/`len` must be exactly a pair previously returned by those functions.
 */
void sassytalkie_free_bytes(uint8_t *ptr, uintptr_t len);

/**
 * The relay room id (= QR session_id) for the active session, or null if not
 * paired. Free with `sassytalkie_free_string`.
 */
char *sassytalkie_relay_room_id(void);

/**
 * Mark the relay connected (true) / disconnected (false). While connected, TX
 * frames are teed into the relay outbound queue for Swift to forward.
 */
void sassytalkie_relay_set_active(bool active);

/**
 * Drain one sealed audio frame to send over the WebSocket. Writes the length to
 * `out_len` and returns a buffer (free with `sassytalkie_free_bytes`), or null
 * when the queue is empty.
 *
 * # Safety
 * `out_len` must be a valid pointer to a usize.
 */
uint8_t *sassytalkie_relay_poll_outbound(uintptr_t *out_len);

/**
 * Build the next OP_HEARTBEAT frame to send over the WebSocket (~every 2 s).
 * Free with `sassytalkie_free_bytes`. Null only if not initialized.
 *
 * # Safety
 * `out_len` must be a valid pointer to a usize.
 */
uint8_t *sassytalkie_relay_heartbeat_frame(uintptr_t *out_len);

/**
 * Process a binary frame received from the relay WebSocket: decrypt + unpack +
 * decode + play. Returns true if it was a playable audio frame for our channel
 * (false = control/heartbeat from a peer, wrong channel, or not for us).
 *
 * # Safety
 * `ptr` must point to `len` valid bytes.
 */
bool sassytalkie_relay_on_message(const uint8_t *ptr, uintptr_t len);

/**
 * Set current channel
 */
bool sassytalkie_set_channel(uint8_t channel);

/**
 * Get current channel
 */
uint8_t sassytalkie_get_channel(void);

/**
 * Start PTT transmission
 */
bool sassytalkie_ptt_press(void);

/**
 * Stop PTT transmission
 */
bool sassytalkie_ptt_release(void);

/**
 * Connect to a peer device
 */
bool sassytalkie_connect(uint32_t device_id);

/**
 * Disconnect from peer
 */
bool sassytalkie_disconnect(void);

/**
 * Start listening for incoming connections
 */
bool sassytalkie_start_listening(void);

/**
 * Get current state (0=Idle, 1=Connecting, 2=Connected, 3=Transmitting, 4=Receiving)
 */
uint8_t sassytalkie_get_state(void);

/**
 * Process audio input from Swift (AVAudioEngine)
 * 
 * # Safety
 * `audio_data` must point to valid PCM samples
 */
bool sassytalkie_process_audio_input(const int16_t *audio_data, uintptr_t sample_count);

/**
 * Get audio output for Swift (AVAudioEngine)
 * Returns number of samples written
 * 
 * # Safety
 * `buffer` must have space for at least `buffer_size` samples
 */
uintptr_t sassytalkie_get_audio_output(int16_t *buffer, uintptr_t buffer_size);

/**
 * Return the BLE service UUID that Swift should advertise + scan for.
 *
 * # Safety
 * Caller must free the returned string with `sassytalkie_free_string`.
 */
const char *sassytalkie_bt_service_uuid(void);

/**
 * Register a peer discovered by the Swift CoreBluetooth central.
 *
 * # Safety
 * `id` and `name` must be valid NUL-terminated UTF-8 C strings (or null).
 */
bool sassytalkie_bt_device_found(const char *id, const char *name, int32_t rssi);

/**
 * Remove a peer the Swift central reported as lost / disconnected.
 *
 * # Safety
 * `id` must be a valid NUL-terminated UTF-8 C string (or null).
 */
bool sassytalkie_bt_device_lost(const char *id);

/**
 * Number of currently-discovered BLE peers.
 */
uintptr_t sassytalkie_bt_peer_count(void);

/**
 * JSON array of discovered peers: `[{"id":..,"name":..,"rssi":..}, ...]`.
 *
 * # Safety
 * Caller must free the returned string with `sassytalkie_free_string`.
 */
const char *sassytalkie_bt_get_peers_json(void);

/**
 * Mark a peer as the actively-connected device.
 *
 * # Safety
 * `id` must be a valid NUL-terminated UTF-8 C string (or null).
 */
bool sassytalkie_bt_set_connected(const char *id);

/**
 * Clear the active BLE connection.
 */
void sassytalkie_bt_clear_connected(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#ifdef __cplusplus
}  // namespace sassytalkie
#endif  // __cplusplus

#endif  /* SASSYTALKIE_IOS_H */
